version: '3'
services:

  nginx:
    container_name: ${CONTAINER_NAME}__HLE-web
    image: atillay/lemp-nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./www:/var/www/html
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/mime.types:/etc/nginx/mime.types
      - ./log:/var/log/nginx
    restart: unless-stopped

  php:
    container_name: ${CONTAINER_NAME}__HLE-php
    build:
      context: ./conf/Dockerfile
      dockerfile: lemp
    ports:
      - ${SERVER_PORT}:80
      - ${BSYNC_PORT}:3000
      - 8000:8000
    volumes:
      - ./www:/var/www/html
      - ./conf/httpd.conf:/etc/apache2/sites-available/000-default.conf
      - ./conf/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html
    restart: unless-stopped

  db:
    container_name: ${CONTAINER_NAME}__HLE-db
    image: mysql:5.7
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PWD}
      MYSQL_DATABASE: ${DB_NAME}
    restart: unless-stopped

  phpmyadmin:
    container_name: ${CONTAINER_NAME}__HLE-pma
    image: phpmyadmin/phpmyadmin:4.7
    ports:
      - ${PMA_PORT}:80
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_ROOT_PWD}
    restart: unless-stopped