version: '3'
services:

  nginx:
    container_name: ${CONTAINER_NAME}_HLE-web
    image: atillay/lemp-nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/mime.types:/etc/nginx/mime.types
      - ./log:/var/log/nginx
      - ./www:/var/www/html
    restart: unless-stopped

  php:
    container_name: ${CONTAINER_NAME}_HLE-php
    build:
      context: ./conf
      dockerfile: Dockerfile-lamp
    ports:
      - ${SERVER_PORT}:80
    volumes:
      - ./conf/httpd.conf:/etc/apache2/sites-available/000-default.conf
      - ./conf/php.ini:/usr/local/etc/php/php.ini
      - ./www:/var/www/html
    working_dir: /var/www/html
    restart: unless-stopped

  mysql:
    container_name: ${CONTAINER_NAME}_HLE-sql
    image: mysql:5.7
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PWD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped

  phpmyadmin:
    container_name: ${CONTAINER_NAME}_HLE-pma
    image: phpmyadmin/phpmyadmin:4.7
    ports:
      - ${PMA_PORT}:80
    environment:
      PMA_HOST: ${DB_HOST}
    restart: unless-stopped

  maildev:
    container_name: ${CONTAINER_NAME}_HLE-mail
    image: djfarrelly/maildev
    ports:
      - ${MAILDEV_PORT}:80
    restart: unless-stopped