version: '3'
services:

  prestashop:
    container_name: ${CONTAINER_NAME}__HPS-php
    build:
      context: ./conf
      dockerfile: prestashop
    ports:
      - ${SERVER_PORT}:80
      - ${BSYNC_PORT}:3000
    volumes:
      - ./www:/var/www/html
      - ./conf/httpd.conf:/etc/apache2/sites-available/000-default.conf
      - ./conf/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html
    environment:
      PS_DEV_MODE: 1
      PS_FOLDER_ADMIN: ps-admin
      DB_SERVER: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    restart: unless-stopped

  mariadb:
    container_name: ${CONTAINER_NAME}__HPS-db
    build:
      context: ./conf
      dockerfile: mariadb
    ports:
      - ${DB_PORT}:80
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PWD}
      MYSQL_DATABASE: ${DB_NAME}
    restart: unless-stopped

  phpmyadmin:
    container_name: ${CONTAINER_NAME}__HPS-pma
    image: phpmyadmin/phpmyadmin:4.7
    ports:
      - ${PMA_PORT}:80
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${DB_ROOT_PWD}
    restart: unless-stopped