version: '3'
services:

  php:
    container_name: ${CONTAINER_NAME}_HSF-php
    build:
      context: ./
      dockerfile: ./conf/Dockerfile-symfony
    ports:
      - ${SERVER_PORT}:80
      - ${BSYNC_PORT}:3000
      - 8000:8000
    volumes:
      - ./www:/var/www
      - ./conf/httpd-symfony.conf:/etc/apache2/sites-available/000-default.conf
      - ./conf/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www
    restart: unless-stopped

  mysql:
    container_name: ${CONTAINER_NAME}_HSF-sql
    image: mysql:5.7
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PWD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped

  phpmyadmin:
    container_name: ${CONTAINER_NAME}_HSF-pma
    image: phpmyadmin/phpmyadmin:4.7
    ports:
      - ${PMA_PORT}:80
    environment:
      PMA_HOST: ${DB_HOST}
    restart: unless-stopped

  maildev:
    container_name: ${CONTAINER_NAME}_HSF-mail
    image: djfarrelly/maildev
    ports:
      - ${MAILDEV_PORT}:80
    restart: unless-stopped