version: '3'
services:

  php:
    container_name: ${CONTAINER_NAME}__HSF-php
    build:
      context: ./conf
      dockerfile: symfony
    ports:
      - ${SERVER_PORT}:80
      - ${BSYNC_PORT}:3000
      - 8000:8000
    volumes:
      - ./www:/var/www/html
      - ./conf/httpd-symfony.conf:/etc/apache2/sites-available/000-default.conf
      - ./conf/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html
    restart: unless-stopped

  db:
    container_name: ${CONTAINER_NAME}__HSF-db
    image: mysql:5.7
    ports:
      - ${DB_PORT}:80
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PWD}
      MYSQL_DATABASE: ${DB_NAME}
    restart: unless-stopped

  phpmyadmin:
    container_name: ${CONTAINER_NAME}__HSF-pma
    image: phpmyadmin/phpmyadmin:4.7
    ports:
      - ${PMA_PORT}:80
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_ROOT_PWD}
    restart: unless-stopped